project:
  name: "monkey_classifier"
  random_seed: 42

data:
  raw_path: "dataset"
  samples_per_class: 50
  split: [0.7, 0.15, 0.15]

model:
  name: ""
  input_size: [224,224,3]
  epochs: 20
  batch_size: 32

web:
  port: 5000
  debug: true