version: '3.8'

services:
  monkey-classifier:
    build:
      context: ..  # контекст сборки - корень проекта
      dockerfile: docker/Dockerfile  # путь к Dockerfile
    image: monkey-classifier:latest
    container_name: monkey-classifier
    ports:
      - "8501:8501"
    volumes:
      - ../models:/app/models          
      - ../full_dataset:/app/data      
      - ../db:/app/db                 
      - ../web:/app/web          
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_MAXUPLOADSIZE=1000
    restart: unless-stopped